# Generated by Django 3.1.4 on 2021-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
    ]
