# Generated by Django 3.1.4 on 2021-01-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
