# Generated by Django 3.1.4 on 2021-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210106_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人类', 'verbose_name_plural': '人类'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目计划', 'verbose_name_plural': '项目计划'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='tb_projectss',
        ),
    ]
