# Generated by Django 3.1.4 on 2021-01-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210107_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
